FOSS-Community/fosscu.org

FOSSC_About.html
assets/Event-1.html
index.html
teams/index.html
teams/teams.html

add some meta tag and deafult image

---

styles.css

Their was a overflow issue in mobile view

Updated css

---

index.html

Updated by Aditya Pachauri

---

index.html

Reverts FOSS-Community/website-fossc#14

Revert "Updated by Aditya Pachauri"

---

package.json
src/App.js
src/components/Navbar.jsx
src/pages/Homepage.jsx
src/pages/Team.jsx
tailwind.config.js
yarn.lock

Added FlowBite components to the website teams page.

Addition of Flowbite components to the Website.

---

src/data/community-guidelines.json
src/data/faq.json
src/data/team.json

Added Content For FAQ, Team-Page, Community-Guidelines in Json format.

Added Content For FAQ, Team-Page, Community-Guidelines

---

src/components/Footer.jsx
src/pages/Homepage.jsx
src/pages/Team.jsx
tailwind.config.js

@Mr-Sunglasses  - Added Footer to the Website, its component to Homepage and Some Minor Changes .

Added Footer and Minor Changes.

---

src/components/Cards.jsx

Added Card Component For the Website.

Added Card Component 📇

---

src/components/Contact.jsx

I have connect the contact from with the Api ps review it.....

added backend

---

src/components/Navbar.jsx

updated navbar.jsx

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Added CODE_OF_CONDUCT.md and CONTRIBUTING.md

---

src/components/Footer.jsx

I've made some updates to the codebase to add the source code for the "about" and "blog" sections, which were not present earlier. These changes can be found in the "src" folder.

Added source code for about and blog sections

---

src/components/Guide_Element.jsx

Made the page responsive...
SCREENSHOTS

Added responsiveness

---

src/App.jsx
src/components/Faq.jsx
src/components/Footer.jsx
src/pages/Contacts.jsx
src/pages/Faqs.jsx

<h1><b>Screenshots:</b></h1>
<h2>Happy to work on this :smiley_cat:  </h2>

faq page & contact links added

---

Dockerfile

- time: 86 sec
- size: 973 MB
- time: 95 sec
- size: _416_ MB

Updated Dockerfile to Multistage build

---

src/components/Hero.jsx

Pardon the silly mistake, last time an extra letter got added by mistake in the link. therefore it was not working

link fixed

---

.github/ISSUE_TEMPLATE/bug.yml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

Fixed repetitive title

---

src/components/Footer.jsx

Here I updated this 
(https://user-images.githubusercontent.com/103263909/234910689-1ce70a66-66ef-425c-8bff-803a02ef83f2.png)
to this.
(https://user-images.githubusercontent.com/103263909/234910778-dd278b67-42d1-45ef-bb95-fc1905bedabb.png)

Footer Updated  #138

---

.github/ISSUE_TEMPLATE/feature.yml

Fixed the structure of feature request template and tailored it according to the repository.

Fixed feature request template

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

Fixed both the issue templates.
Tested using GitHub issue template.

Fixed both the issue templates

---

pnpm-lock.yaml
src/components/Hero.jsx

I have created a button for Doubt Scheduling. If anyone want to book their slot for Doubt then they can book by clicking on the button.
issue no - #144

Created a button for Doubt Schedule

---

src/components/About.jsx

There was an unexpected space before the bracket in the community description and i have corrected that.
Fixes # (issue)

Fixed brackets at FOSS

---

src/components/Hero.jsx

fixed button alignment

---

src/components/Faq.jsx
src/components/Hero.jsx

I have aligned image and text both in center in the homepage of fosscu

---

src/components/Hero.jsx

fixed small bug
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #161 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
- [x ] My code follows the style guidelines of this project

Update Hero.jsx : This fixes the bug that was causing the nav bar buttons to become inactive.

---

src/assets/roadmap/roadmap.css
src/components/TeamsComponent.jsx
src/data/teams.json
src/pages/Roadmap.jsx
src/pages/Team.jsx

@Mr-Sunglasses sir, I'm happy to report that I have completed this.

added props to team components

---

src/components/Navbar.jsx
src/pages/Contacts.jsx

<li><b> I added a hovering effect to the icons so that when a user hovers over them, they change color or become slightly larger to indicate that they can be clicked on. I also added a similar effect to the navbar options so that when a user hovers over them, they become highlighted to indicate which page they will be taken to.
<li> To improve the user experience, I suggest adding target="_blank" to the links on the website. This would enable users to open links in a new tab with ease, and ensure that the original page remains accessible.
<li> I also added 'Handbook' button on the mobile view of website.
@Mr-Sunglasses @akshatcoder-hash   Sir, I solved this..if you need any more changes please mention it. 
[Screencast from 05-05-2023 02_14_34 AM …

Enhancements to website 

---

src/components/Footer.jsx

Hovering to footer

---

src/components/Navbar.jsx
src/components/Roadmaps.jsx
src/data/frontend.json
src/pages/Roadmap.jsx

#155 
<h3> The footer and nav components overlapping the sidebar component of the Resource Section. I have made the necessary changes to fix the issue and have thoroughly tested the changes to ensure they do not introduce any other issues.</h3>
<br>
<br>
#171 
<h3>I have fixed the issue of the sidemenu bar not being visible when the sidebar gets hidden. The necessary changes have been made to ensure that the sidemenu bar is visible and easily accessible on mobile view or smaller screens when the sidebar gets hidden.</h3>
@Mr-Sunglasses sir , Please let me know if you have any further feedback or concerns.

fixed sidebar component of resource section :green_heart: 

---

src/components/Roadmaps.jsx
src/data/data.json
src/data/frontend.json
src/pages/Roadmap.jsx

I have made some changes to the code for the resource page's sidebar component. The previous code was quite lengthy, but I have optimized it by adding props to the component. This will make it more modular and easier to maintain in the future.
Additionally, I have added some more content , which will enhance the user experience and provide them with more relevant information.
@Mr-Sunglasses sir, Please review my changes and let me know if you have any feedback or suggestions. I am open to making further improvements to the code.

added more props to the resource page component

---

src/components/Navbar.jsx

<b>I noticed that there were quite a few sections in the navbar, and it didn't look good. To address this, I added a dropdown menu to the navbar, making it easier for users to find the sections they're looking for. And I also added Calender option in the navbar
#173 #169 
@Mr-Sunglasses  Sir, please review this one.

Added Dropdown Menu in Navbar

---

index.html

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

added google/ search engine tags

---

src/components/TeamsComponent.jsx
src/data/teams.json

<li> <b>To improve the user experience, I suggest adding "target":"_blank" and  "rel": "noopener noreferrer" to the links on the Team section. This would enable users to open links  of profile of team members in a new tab with ease, and ensure that the original page remains accessible. 
@Mr-Sunglasses , Sir please have a look at this

Profiles of the team members are opening  in a new tab instead of same tab.

---

src/components/About.jsx
src/components/Newsletter.jsx

style: added hover effect to Notify button in src/components/Newsletter.jsx
style: added hover effect to Connect With Us button in src/components/About.jsx
Style update

style: added hover effect to Notify, Connect With Us button

---

src/components/Hero.jsx

@Mr-Sunglasses  @akshatcoder-hash

Resolved Button Click Behavior Issue 

---

src/App.jsx
src/components/RedirectToConf.jsx

feat: Implemented external redirect to FOSSConf23

---

src/data/teams.json

Updated Team 🦁

---

src/data/teams.json
src/pages/Contacts.jsx

add: Matrix on contacts page

---

index.html
src/components/About.jsx
src/components/Footer.jsx
src/pages/AboutOrg.jsx

This PR fixes #233
Corrected the full form of FOSS on all the pages, added the linked icon in footer. :)

[Bug] : Full form corrected, linkedin icon added

---

src/App.jsx
src/components/Navbar.jsx
src/pages/GitHubRepoCard.jsx
src/pages/Shipyard.jsx
yarn.lock

added shipyard page

---

src/components/Contact.jsx
src/pages/Contacts.jsx
yarn.lock

fix: Broken Contacts page to Contact component

---

package.json
src/App.jsx
src/pages/PageNotFound.jsx
yarn.lock

feat: Add new 404 page with some eastereggs 🐣

---

.github/pull_request_template.md

This PR updates the pull_request_template.md file to remove references that were mistakenly pointing to another repository. The previous template included incorrect references.

Fix: pull_request_template

---

.dockerignore
Dockerfile
Dockerfile.dev
README.md
package.json

Dockerized the project with the following commands:
`docker:build` : Build production image.
`docker:run` : Run production container.
`docker:build-run` : Run production image .
`docker:dev-build` : Build development image.
`docker:dev` : Run development container.
`docker:dev-build-run` : Run development container after building the image.

feat: Dockerized the project

---

_redirects

URL shortner via netlify.
fix: #325 
- **Feature 1**: Description of feature 1 changes.
- **Feature 2**: Description of feature 2 changes.
- **Bugfix**: Description of any bug fixes.

feat: Add URL shortner via Netlify

---

_redirects

closes: #327 
- **Feature 1**: Description of feature 1 changes.
- **Feature 2**: Description of feature 2 changes.
- **Bugfix**: Description of any bug fixes.

fix: Delete _redirects and move to /public/_redirects

---

public/_redirects

#327 
- **Feature 1**: Description of feature 1 changes.
- **Feature 2**: Description of feature 2 changes.
- **Bugfix**: Description of any bug fixes.

fix: change redirects directory

---

Dockerfile

fix: Docker built image
Fixed the breaking changes oof docker
Run Commands
docker:build-run : Build production image.
docker:dev-build-run : Run development container after building the image.

fix: Docker built image

---

src/components/Contact.jsx
vite.config.ts

Fixed Broken Contact Page
The env variables were not loadding due to vite config 
- **1**: Changed vite config file
- **2**: Added env variables

fix:Contact Page + .env

---

index.html
package-lock.json
package.json
src/components/Contact.jsx
yarn.lock

Added Airtable API
Added the Airtable API in the Contact form submission
#345

[FEAT]: Added Airtable API

---

src/app/shipyard/README.md
src/app/shipyard/page.tsx
src/components/ShipyardIntro.tsx
src/components/ui/hover-border-gradient.tsx

Fixes #381  by @RaghavRR
Fixes #385 by @RaghavRR
This pull request completes the **Shipyard Page** by adding the introduction section and updating the **"Submit your project"** button link to make it functional.
The new Shipyard intro explains the initiative and its purpose, while the button directs users to the correct **Shipyard GitHub repository**, where they can submit their projects after fork.
The README.md file for the Shipyard project currently does not exist in the repository at the specified location (src/app/shipyard/README.md).
Once this pull request is reviewed and merged, I will create the necessary README.md file to include detailed project submission instructions, guidelines, and additional information for users.
In the meantime, please note that this file will be created …

Fix: Add Shipyard Intro and Update 'Submit Your Project' Button
